### PR TITLE
Update configure.py

### PR DESCRIPTION
**Pull request by BdMdesigN**
Add Systemsettings (control.exe) to the Wine Configuration in the configure.py

### CODE REVIEW

**Comment by qparis** [comment]
Thank you,

Can you upload a screenshot please?

**Comment by BdMdesigN** [comment]
Yes i will upload 2 Screenshots later today, no problem

**Comment by BdMdesigN** [comment]
Here we go:

systemsettings
systemsettings2

**Comment by qparis** [comment]
Can we try to find a consistant icon with the other ones? (i.e. From Faenza)

**Comment by BdMdesigN** [comment]
Yes you can, the wine icon is only a placeholder and the translations are not done yet

**Comment by BdMdesigN** [comment]
Maybe this one:

control-center2.png:
control-center2

or control-center2.xpm?

**Comment by qparis** [comment]
Yeah it sounds good! Can you do it?

**Comment by BdMdesigN** [comment]
ok

**Comment by petchema** [comment]
For the record, this would fill a feature request in PlayOnLinux tracker:
https://www.playonlinux.com/en/issue-4198.html

**Comment by BdMdesigN** [comment]
I close this request and open later a new

**Pull request closed without merging**
