### PR TITLE
Implement support for Python 3 and wxPython 4

### PR DESCRIPTION
**Pull request by swt2c**
I do realize that POL 4 is no longer being developed.  However, I developed this Python 3 port for Debian as it was easier than trying to package Phoenicis for the time being.  I figure I'd send it here anyway in case it is useful to someone.

### CODE REVIEW

**Comment by qparis** [comment]
Waho good job! I wanted to tackle this issue but you did it before! This is a really amazing surprise.

I promes I’ll review and redeploy your code in the few coming days.

Thanks a lot!

**Comment by swt2c** [comment]
Glad to know it will be useful.  :-)  Let me know if you find anything you want me to fix.  It has only seen limited testing in Debian so far.

**Comment by qparis** [comment]
No worries. It should be a good start in any case. This code base clearly needs a good cleaning, and your contribution will surely help

**Comment by qparis** [comment]
POL 4.4 will be deployed by the end of the week. Thanks a lot

**Pull request merged**
