### PR TITLE
Add documentation to playonlinux

### PR DESCRIPTION
**Pull request by jkonecny12**
These are not in playonlinux git and but I found them in the Fedora
package.
Taken from there.

It's good to have manual here for the packaging.

### CODE REVIEW

**Comment by qparis** [comment]
Thank you :)

**Comment by jkonecny12** [comment]
WOW that was quick :)

**Comment by petchema** [comment]
playonlinux-daemon is not part of PlayOnLinux package though

**Comment by jkonecny12** [comment]
I see hmm... I took all the man pages what are in package for Fedora. So this could be removed though.

**Comment by petchema** [comment]
Either that, or we should have a closer look at this contribution, maybe it doesn't make sense only on Fedora...

**Comment by qparis** [comment]
The daemon was part of PlayOnLinux before. It is just that it has not been removed from the doc apparently

**Pull request merged**
